Avoid warnings on Python 3.8 and up by not passing in the loop to
``asyncio.wait_for()``.
